<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

In [2]:
# subsetting: select something from a list/array
# indexing: selecting one element
# slicing: select a range of elements

In [1]:
import numpy as np

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [3]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array

#specify 2 indices to indicate start and end for slicing

print(x[0:4]) #gives 4-0 elements, 1st to 4th position
print(x[2:6]) #gives 6-2 elements, 2nd to 5th position
print(x[1:6:2]) #steps of 2
print(x[5:2:-1]) #in reverse
print(x[:-4]) #everything except last 4 (everything backwards from f6)
print(x[::-1])

#in general, [a:b] will give all elements from position a to b-1 || gives b-a elements in total (a-b+1)\
#think of it as being like [a,b) in set notation

['a1' 'b2' 'c3' 'd4']
['c3' 'd4' 'e5' 'f6']
['b2' 'd4' 'f6']
['f6' 'e5' 'd4']
['a1' 'b2' 'c3' 'd4' 'e5' 'f6']
['j10' 'i9' 'h8' 'g7' 'f6' 'e5' 'd4' 'c3' 'b2' 'a1']


## 1.2 Arrays only | Subsetting by masking

In [25]:
py_list = [1, 2, 3, 4, 5, 6, 7, 8, 9 ,10]
np_array = np.array(py_list)
my_mask = (np_array > 3) & (np_array < 8)    # cannot use 'and' as it is a python function, wont work for numpy
my_mask
#mask shows all elements that fit certain parameters as true

array([False, False, False,  True,  True,  True,  True, False, False,
       False])

In [29]:
np_array[my_mask] #new array showing only true elements

array([4, 5, 6, 7])

In [34]:
np_array[(np_array > 3) & (np_array < 8)] #faster method

array([4, 5, 6, 7])

In [42]:
np_array[(np_array < 3) | (np_array > 8)] # | means 'OR'

array([ 1,  2,  9, 10])

In [37]:
np_array[~(np_array > 3)]                 # '~' means 'NOT'
#~ is used to invert mask, give all elements that are NOT  over 3

array([1, 2, 3])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [5]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

py_list_2d[3] #set of number and letter at 4th pos
np_array_2d[3] #set of number and letter at 4th pos

array(['4', 'D'], dtype='<U21')

In [50]:
py_list_2d[3][0]
np_array_2d[3, 0]
#both show first element at 4th pos
#lists don't use comma, arrays do

np.str_('4')

In [57]:
py_list_2d[0][0],py_list_2d[0][1]


(1, 'A')

In [8]:
py_list_2d[:3]
np_array_2d[:3]
# both show 1st 3 elements

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U21')

In [13]:
np_array_2d[:3,0]

array(['1', '2', '3'], dtype='<U21')

In [70]:
py_list_2d[:3]  # first 3 sets
py_list_2d[:3][0] # all sets before pos 2 AND 1st set

np_array_2d[:3,0] # first element in each set, for the first 3 sets

array(['1', '2', '3'], dtype='<U21')

In [18]:
py_list_2d[3:6][0] #within the sub-list of 3-6, pulls the pair at the first pos
np_array_2d[3:6, 0] #pulls first element from sub-list of pos 3-6
np_array_2d[:, 0] #all first elements

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

## 1.4 Growing lists

In [ ]:
#numpy arrays are great for math operations as long as the size isn't changed

In [19]:
x=[1, 2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [71]:
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x
x=[1]
x+= [2]
x+= [3]
x+= [4]
x
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

#.append is fastest

[1, 2, 3, 4]

In [22]:
x = [1, 2, 3]
x += [4, 5, 6] #same result as extend to get [1,2,3,4,5,6]
x
#x=[1, 2, 3]
#x.extend([4, 5, 6]) #naturally adds 4,5,6 to original x list to get [1,2,3,4,5,6]
#x
#x=[1, 2, 3]
#x.append([4, 5, 6]) #adds the list [4,5,6] to the original x list to get [1,2,3,[4,5,6]]
#x

[1, 2, 3, 4, 5, 6]

# Some loose ends

## 1.5 Tuples

In [74]:
a = (1,2,3) # Define tuple

print(a[0])
#tuples use () e.g (a,b,c)
#tuples are immutable and do not change after being made

1


In [75]:
# The following will NOT work
a[0]=-1
a[0]+= [10]

TypeError: 'tuple' object does not support item assignment

## 1.6 Be VERY careful when copying

In [79]:
x = [1,2,3]
y = x.copy()


[1, 2, 3]

## Footnotes