<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

In [22]:
import numpy as np

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

In [4]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

#note use of curly brackets for dictionary
#order matters for lists (black widow and nat romanoff must be in the same position)

## 1.2 Accessing data from a list (or array)

In [7]:
py_real_names [0]
py_super_names [2]

#python is 0-indexed, starts counting from 0
#note use of [] to access list

'Stephen Strange'

In [8]:
py_super_names[2]    # Forward indexing 
                     # We need to know the size 
                     # beforehand for this to work.

'Doctor Strange'

In [9]:
py_super_names [-1]

'Doctor Strange'

In [5]:
np_super_names [0] = 'Yippe'
print(np_super_names)

['Yippe' 'Iron Man' 'Doctor Strange']


## 1.3 Accessing data from a dictionary

In [12]:
superhero_info["Natasha Romanoff"]

'Black Widow'

In [13]:
superhero_info.keys() #.keys() pulls all the keys (elements before the colon)

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [14]:
superhero_info.values() #.values pulls all the values(elements after the colon)

#dictionaries are not commutative, can only use keys to pull values and not the other way around

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

## 1.4 Higher dimensional lists

In [16]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

#note use of [[]] for 2d lists

In [18]:
py_superhero_info[0]

#for 2d lists, indexing pulls 2 elements in 1st position

['Natasha Romanoff', 'Black Widow']

# 2 Lists vs. Arrays

## 2.1 Size

In [30]:
py_list_2d = [['1,A'], ['2,B'], ['3,C'], ['4,D'], ['5,E'], ['6,F'], ['7,G'], ['8,H'], ['9,I'], ['10,J']]
np_array_2d = np.array(py_list_2d)

#len() can be used to find the number of elements in a list or array
#for 2d lists/arrays, len() pulls all the sets of elements

In [31]:
len(py_list_2d)


10

In [32]:
len(np_array_2d)

10

In [23]:
np_array_2d.shape

--> #IMPORTANT: only use () after a . if it is a function and not if its an attribute

(10, 2)

## 2.2 Arrays are fussy about type

In [38]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)
#arrays store only one type of element

In [39]:
py_list

[1, 1.5, 'A']

In [40]:
np_array

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [41]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

In [43]:
py_list + 10  #does not work

TypeError: can only concatenate list (not "int") to list

In [46]:
np_array + 10 #adds 10 to all elements

array([11, 12, 13, 14, 15])

## 2.4 Adding another list

In [47]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [49]:
py_list_1 + py_list_2 #concantentation, extends list

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [50]:
np_array_1 + np_array_2 #adds elements together

array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [25]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [53]:
py_list*2 #duplicates elements

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [55]:
np_array*2 #multiplies elements

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [56]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [58]:
py_list**2 # ** for exponentiation

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [62]:
np_array**2

array([ 1,  4,  9, 16, 25])

## 2.7 Asking questions

In [63]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [64]:
py_list ==3 #Works, but what is the question?

False

In [65]:
np_array == 3

array([False, False,  True, False, False])

In [66]:
np_array >3

array([False, False, False,  True,  True])

## 2.8 Mathematics

In [67]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [33]:
sum(py_list)     # sum() is a base Python function
max(py_list)     # max() is a base Python function
min(py_list)     # min() is a base Python function

1

In [74]:
x=sum(np_array)

In [75]:
y=30
y/x

np.float64(2.0)

In [81]:
py_list_1 = [[1,1],[2,2],[3,3],[4,4]]
np_array_1 = np.array(py_list_1)

In [87]:
np_array_1.sum()

np.int64(20)

In [86]:
np_array_1.sum(axis=1)

array([2, 4, 6, 8])

In [34]:
np_array.mean()

np.float64(3.0)

In [35]:
np_array.std()

np.float64(1.4142135623730951)

## Footnotes

--> #IMPORTANT: in general, an operation on a list works on the **whole** list. In contrast, an operation on an array works on the **individual elements** of the array